export const categoryData =[
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Chicken',
        image:'https://www.themealdb.com/images/category/chicken.png'
    }
]

export const mealData =[
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Starter1',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef1',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert1',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Starter2',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef2',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert2',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Starter3',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef3',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert3',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
]
