export const categoryData =[
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Chicken',
        image:'https://www.themealdb.com/images/category/chicken.png'
    }
]

export const mealData =[
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
    {
        name:'Starter',
        image:'https://www.themealdb.com/images/category/starter.png'
    },
    {
        name:'Beef',
        image:'https://www.themealdb.com/images/category/beef.png'
    },
    {
        name:'Dessert',
        image:'https://www.themealdb.com/images/category/dessert.png'
    },
]
